export var ServersConstant = [
  {
    name: 'abc',
    rating: 12,
    languages: ['Ro'],
    category: 'OldSchool',
    focus: 'pvp',
    banner: '../../../../../assets/login-background.jpg',
    playerBase: 32155,
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo aspernatur, eligendi adipisci accusamus ipsam unde consectetur nesciunt laboriosam ut pariatur quo asperiores rem iure, error sunt tempora hic odit alias earum commodi. Laborum molestias corporis doloribus corrupti minus quos ut recusandae quod est tempora repudiandae iure esse consectetur odit vel iste ipsum quasi, aspernatur debitis rerum explicabo ratione hic delectus magnam! Necessitatibus vero beatae ab nobis fugiat nihil autem porro atque incidunt explicabo blanditiis aperiam aut accusamus repellendus, iusto placeat qui vitae amet. Exercitationem doloremque ex natus nisi perferendis a modi tempore voluptate quisquam facere, minima facilis? Magni, recusandae natus!',
  },
  {
    name: 'acb',
    rating: 3,
    languages: ['Ger'],
    category: 'OldSchool',
    focus: 'pvp',
    banner: '../../../../../assets/background1.jpg',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo aspernatur, eligendi adipisci accusamus ipsam unde consectetur nesciunt laboriosam ut pariatur quo asperiores rem iure, error sunt tempora hic odit alias earum commodi. Laborum molestias corporis doloribus corrupti minus quos ut recusandae quod est tempora repudiandae iure esse consectetur odit vel iste ipsum quasi, aspernatur debitis rerum explicabo ratione hic delectus magnam! Necessitatibus vero beatae ab nobis fugiat nihil autem porro atque incidunt explicabo blanditiis aperiam aut accusamus repellendus, iusto placeat qui vitae amet. Exercitationem doloremque ex natus nisi perferendis a modi tempore voluptate quisquam facere, minima facilis? Magni, recusandae natus!',
  },
  {
    name: 'acb1',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server3',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server4',
    rating: 3,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server5',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server6',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server7',
    rating: 5,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server8',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server9',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server10',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server11',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server12',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server13',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server14',
    rating: 1,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server15',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro', 'Ger'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server16',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server17',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Server18',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: 'pve',
    banner: '../../../../../assets/login-background.jpg',
  },
];
