export var ServersConstant = [
  {
    name: 'Thor Legends Reborn',
    rating: 12,
    languages: ['Ro'],
    category: 'OldSchool',
    focus: ['pvp'],
    banner: '../../../../../assets/login-background.jpg',
    playerBase: 32155,
    isPremium: true,
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo aspernatur, eligendi adipisci accusamus ipsam unde consectetur nesciunt laboriosam ut pariatur quo asperiores rem iure, error sunt tempora hic odit alias earum commodi. Laborum molestias corporis doloribus corrupti minus quos ut recusandae quod est tempora repudiandae iure esse consectetur odit vel iste ipsum quasi, aspernatur debitis rerum explicabo ratione hic delectus magnam! Necessitatibus vero beatae ab nobis fugiat nihil autem porro atque incidunt explicabo blanditiis aperiam aut accusamus repellendus, iusto placeat qui vitae amet. Exercitationem doloremque ex natus nisi perferendis a modi tempore voluptate quisquam facere, minima facilis? Magni, recusandae natus!',
  },
  {
    name: 'Zenit - Beyond Limits',
    rating: 3,
    languages: ['Ger'],
    category: 'OldSchool',
    focus: ['pvp'],
    banner:
      'https://metins-images.s3.amazonaws.com/media/server_images/Banner1434246577468x190.gif',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo aspernatur, eligendi adipisci accusamus ipsam unde consectetur nesciunt laboriosam ut pariatur quo asperiores rem iure, error sunt tempora hic odit alias earum commodi. Laborum molestias corporis doloribus corrupti minus quos ut recusandae quod est tempora repudiandae iure esse consectetur odit vel iste ipsum quasi, aspernatur debitis rerum explicabo ratione hic delectus magnam! Necessitatibus vero beatae ab nobis fugiat nihil autem porro atque incidunt explicabo blanditiis aperiam aut accusamus repellendus, iusto placeat qui vitae amet. Exercitationem doloremque ex natus nisi perferendis a modi tempore voluptate quisquam facere, minima facilis? Magni, recusandae natus!',
  },
  {
    name: 'Shiva.International',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner:
      'https://metins-images.s3.amazonaws.com/media/server_images/Banner1434246577468x190.gif',
    isPremium: true,
  },
  {
    name: 'Ashiro2',
    rating: 4,
    isPremium: true,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Loranda2 - Hype Server - Start Soon',
    rating: 3,
    isPremium: true,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Azyrah',
    rating: 4,
    isPremium: true,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Age of Magis',
    rating: 2,
    isPremium: true,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Osiris2 - Power Unleashed',
    rating: 5,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Astra2',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Sineria - die wieder zum Leben erweckte Nostalgie',
    rating: 4,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: '~ SEISHIN ~ Follow your soul ~ JOIN NOW ~',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Alderoth | Start Date: 22.12.2023 |',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Yeogsa - Classic Hardcore Experience - New Administration',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Land of Heroes EU',
    rating: 2,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Old Metin2 | Untouched Metin2',
    rating: 1,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Aegis2',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro', 'Ger'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'MT2 AlphA - Server PvM - PvP Level 250 Easy',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Metin2SG!',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
  {
    name: 'Metin2Pika International Server -250level- Farm for DC',
    rating: 0,
    category: 'NewSchool',
    languages: ['Ro'],
    focus: ['pve'],
    banner: '../../../../../assets/login-background.jpg',
  },
];
